// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ingresos y Egresos")]
    public partial class IngresosYEgresosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Ingresos y Egresos", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "IngresosEngresos.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
  #line hidden
#line 4
    await testRunner.GivenAsync("el usuario accede al sistema de Ingresos/Egresos \'http://161.132.67.82:31097/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.WhenAsync("el usuario inicia sesion con usuario \'admin@plazafer.com\' y contrasena \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
    await testRunner.AndAsync("accede al modulo \'Tesoreria y Finanzas\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
    await testRunner.AndAsync("accede al submodulo \'Ingresos/Egresos\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de Ingresos y Egresos")]
        [NUnit.Framework.CategoryAttribute("RegistrarIngresoEgreso")]
        [NUnit.Framework.TestCaseAttribute("1", "01/11/2025", "01/11/2025", "Cobros", "Ingreso", "Empleado", "60587924", "76184356", "NOTA DE INGRESO", "120", "Prueba automatizada", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("2", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "0", "Prueba automatizada", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("3", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "0", "100", "Prueba automatizada", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("4", "01/11/2025", "01/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "120", "Prueba automatizada", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("5", "02/11/2025", "02/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "150", "Registro valido", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("6", "04/11/2025", "04/11/2025", "Pagos", "Egreso", "Proveedor", "76184356", "75521712", "NOTA DE EGRESO", "250", "Datos completos", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("7", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "80", "Validacion correcta", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("8", "06/11/2025", "06/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "200", "Flujo normal", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("9", "08/11/2025", "08/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "300", "Registro exitoso", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("10", "09/11/2025", "09/11/2025", "Cobros", "Ingreso", "Empleado", "76184356", "75521712", "NOTA DE INGRESO", "60", "Prueba flujo normal", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("11", "10/11/2025", "10/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "500", "Verificacion correcta", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("12", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "0", "Sin importe", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("13", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "0", "0", "76184356", "NOTA DE EGRESO", "100", "Falta autorizado", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("14", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "0", "NOTA DE EGRESO", "100", "Falta pagador", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("15", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "0", "100", "Sin documento", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("16", "01/11/2025", "02/11/2025", "0", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Tipo de operacion faltante", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("17", "01/11/2025", "01/11/2025", "Cobros", "0", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Sin tipo registro", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("18", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "0", "0", "0", "0", "Todo vacio", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("19", "01/11/2025", "01/11/2025", "Cobros", "Ingreso", "0", "0", "76184356", "0", "0", "Sin datos", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("20", "02/11/2025", "01/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "150", "Fecha inicial mayor", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("21", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "0", "0", "0", "0", "0", "Caso extremo", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("22", "12/11/2025", "12/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "75521712", "NOTA DE INGRESO", "95", "Registro de cliente", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("23", "13/11/2025", "13/11/2025", "Pagos", "Egreso", "Cliente", "12345678", "76184356", "NOTA DE EGRESO", "30", "Pago a cliente", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("24", "14/11/2025", "14/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "0", "NOTA DE INGRESO", "45", "RUC Pagador faltante", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("25", "15/11/2025", "15/11/2025", "Pagos", "Egreso", "Proveedor", "0", "76184356", "NOTA DE EGRESO", "70", "RUC Autorizado faltante", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("26", "16/11/2025", "16/11/2025", "Cobros", "Egreso", "Cliente", "12345678", "75521712", "NOTA DE EGRESO", "10", "Tipo de registro incorrecto", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("27", "17/11/2025", "17/11/2025", "Pagos", "Ingreso", "Proveedor", "75521712", "76184356", "NOTA DE INGRESO", "15", "Tipo de registro incorrecto", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("28", "18/11/2025", "18/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "15000", "Importe grande", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("29", "19/11/2025", "19/11/2025", "Pagos", "Egreso", "Empleado", "75521712", "76184356", "NOTA DE EGRESO", "1", "Importe m�nimo", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("30", "20/11/2025", "20/11/2025", "Cobros", "Ingreso", "Cliente", "0", "0", "NOTA DE INGRESO", "100", "Solo tipo y importe", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("31", "21/11/2025", "21/11/2025", "Cobros", "Ingreso", "Empleado", "123", "76184356", "NOTA DE INGRESO", "100", "RUC autorizado invalido", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("32", "22/11/2025", "22/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "999", "NOTA DE EGRESO", "100", "RUC pagador inv�lido", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("33", "23/11/2025", "23/11/2025", "Cobros", "Ingreso", "Cliente", "ABCDEFGH", "76184356", "NOTA DE INGRESO", "100", "RUC con letras", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("34", "24/11/2025", "24/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "-100", "Importe negativo", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("35", "25/11/2025", "25/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "0.5", "Importe decimal", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("36", "26/11/2025", "26/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "999999999", "Importe muy grande", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("37", "01/01/2025", "01/01/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Fecha inicio de a�o", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("38", "31/12/2025", "31/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Fecha fin de a�o", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("39", "29/02/2024", "29/02/2024", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "100", "A�o bisiesto", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("40", "01/11/2024", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Rango de un a�o", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("41", "27/11/2025", "27/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Documento FACTURA", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("42", "28/11/2025", "28/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "BOLETA", "100", "Documento BOLETA", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("43", "29/11/2025", "29/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "RECIBO", "100", "Documento RECIBO", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("44", "0", "0", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Sin fechas", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("45", "01/11/2025", "0", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Sin fecha final", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("46", "0", "01/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "100", "Sin fecha inicial", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("47", "30/11/2025", "30/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Sin observaci�n", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("48", "01/12/2025", "01/12/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n muy larga", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("49", "02/12/2025", "02/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "75521712", "NOTA DE EGRESO", "100", "Mismo RUC autorizado y pagador", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("50", "03/12/2025", "03/12/2025", "Pagos", "Egreso", "Empleado", "75521712", "0", "NOTA DE EGRESO", "100", "Egreso sin beneficiario", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("51", "04/12/2025", "04/12/2025", "Pagos", "Egreso", "Cliente", "0", "76184356", "NOTA DE EGRESO", "100", "Egreso sin autorizado", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("52", "05/12/2025", "05/12/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n con <script>alert(\'XSS\')</script>", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("53", "06/12/2025", "06/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Observaci�n con \' OR \'1\'=\'1", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("54", "07/12/2025", "07/12/2025", "Cobros", "Ingreso", "Empleado", "SPACE75521712SPACE", "76184356", "NOTA DE INGRESO", "100", "RUC con espacios", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("55", "08/12/2025", "08/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "SPACE76184356SPACE", "NOTA DE EGRESO", "100", "RUC pagador con espacios", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("56", "09/12/2025", "09/12/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "100.00", "Importe con decimales", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("57", "10/12/2025", "10/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100,50", "Importe con coma", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("58", "11/12/2025", "11/12/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "ABC", "Importe no num�rico", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("59", "32/01/2025", "32/01/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "D�a inv�lido", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("60", "01/13/2025", "01/13/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Mes inv�lido", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("61", "29/02/2025", "29/02/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "100", "Fecha inexistente", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("62", "12/12/2025", "12/12/2025", "Cobros", "Ingreso", "Empleado", "1234567", "76184356", "NOTA DE INGRESO", "100", "RUC 7 digitos DNI", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("63", "13/12/2025", "13/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "12345678", "NOTA DE EGRESO", "100", "RUC 8 d�gitos DNI", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("64", "14/12/2025", "14/12/2025", "Cobros", "Ingreso", "Cliente", "7552171299", "76184356", "NOTA DE INGRESO", "100", "RUC 10 d�gitos", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("65", "15/12/2025", "15/12/2025", "Pagos", "Egreso", "Proveedor", "755217129999", "76184356", "NOTA DE EGRESO", "100", "RUC 12 d�gitos", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("66", "16/12/2025", "16/12/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Test de performance", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("67", "17/12/2025", "17/12/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "0.01", "Importe m�nimo decimal", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("68", "18/12/2025", "18/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "50.99", "Importe con centavos", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("69", "19/12/2025", "19/12/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "1000000", "Importe un mill�n", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("70", "20/12/2025", "20/12/2025", "Pagos", "Egreso", "Proveedor", "20123456789", "76184356", "NOTA DE EGRESO", "100", "RUC 11 digitos valido", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("71", "05/11/2025", "06/11/2025", "Cobros", "Ingreso", "VARIOS", "00000000", "00000000", "COBRO VARIOS", "100", "Cobro varios efectivo", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("72", "05/11/2025", "06/11/2025", "Cobros", "Ingreso", "VARIOS", "75521712", "76184356", "COBRO VARIOS", "100", "Cobro varios con RUC", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("73", "05/11/2025", "06/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "00000000", "COBRO VARIOS", "100", "Empleado con VARIOS", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("74", "05/11/2025", "06/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Medio GIROS", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("75", "05/11/2025", "06/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "FACTURA", "1000", "Cliente con factura", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("76", "05/11/2025", "06/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE EGRESO", "100", "Documento de egreso en ingreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("77", "05/11/2025", "06/11/2025", "Pagos", "Egreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "100", "Documento de ingreso en egreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("78", "01/11/2025", "30/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Rango 30 d�as", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("79", "01/01/2025", "31/12/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Rango 1 a�o", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("80", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "75521712", "NOTA DE INGRESO", "100", "Mismo RUC autorizado/pagador en ingreso", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("81", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Empleado", "75521712", "75521712", "NOTA DE EGRESO", "100", "Mismo RUC en egreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("82", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "00000000", "76184356", "RECIBO", "50", "Cliente con RUC 00000000", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("83", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "RECIBO", "100", "Recibo en egreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("84", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n vac�a", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("85", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n 500 chars", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("86", "05/11/2025", "06/11/2025", "0", "0", "0", "0", "0", "0", "0", "Todos los campos vac�os", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("87", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "FACTURA", "100", "Factura en ingreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("88", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "BOLETA", "100", "Boleta en egreso", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("89", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Proveedor", "20123456789", "76184356", "NOTA DE INGRESO", "100", "Proveedor como autorizado en ingreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("90", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Cliente", "12345678", "76184356", "NOTA DE EGRESO", "100", "Cliente como autorizado en egreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("91", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "VARIOS", "00000000", "00000000", "COBRO VARIOS", "250", "Cobro varios sin RUC", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("92", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "VARIOS", "75521712", "00000000", "COBRO VARIOS", "100", "VARIOS con RUC autorizado", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("93", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "VARIOS", "00000000", "00000000", "EGRESO VARIOS", "180", "Egreso varios sin beneficiario", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("94", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "VARIOS", "00000000", "76184356", "EGRESO VARIOS", "100", "VARIOS con RUC pagador", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("95", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "RECIBO", "75", "Recibo por cliente", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("96", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Proveedor", "20123456789", "76184356", "RECIBO", "100", "Recibo por proveedor", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("97", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "20123456789", "75521712", "CHEQUE", "500", "Egreso con cheque", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("98", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "CHEQUE", "100", "Cheque en ingreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("99", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "TRANSFERENCIA", "300", "Egreso por transferencia", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("100", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "TRANSFERENCIA", "100", "Transferencia en ingreso", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("101", "01/11/2025", "15/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Rango 15 d�as", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("102", "01/10/2025", "30/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Rango 61 d�as", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("103", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "999999.99", "Importe m�ximo permitido", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("104", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "1000000", "Importe excede l�mite", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("105", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n con 250 caracteres", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("106", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n con 501 caracteres", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("107", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n con &amp;", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("108", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Observaci�n con &lt;", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("109", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "12345678", "NOTA DE INGRESO", "100", "Cliente paga a s� mismo", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("110", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Cliente", "12345678", "12345678", "NOTA DE EGRESO", "100", "Cliente recibe de s� mismo", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("111", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "75521712", "COBRO VARIOS", "100", "Empleado con COBRO VARIOS", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("112", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "20123456789", "20123456789", "EGRESO VARIOS", "100", "Proveedor con EGRESO VARIOS", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("113", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "VARIOS", "00000000", "00000000", "RECIBO", "100", "VARIOS con RECIBO", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("114", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "VARIOS", "00000000", "00000000", "BOLETA", "100", "VARIOS con BOLETA", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("115", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "FACTURA", "1000", "Factura en ingreso (inv�lido)", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("116", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "RECIBO", "100", "Recibo en egreso (inv�lido)", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("117", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "BOLETA", "100", "Boleta en ingreso (inv�lido)", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("118", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Empleado", "75521712", "76184356", "FACTURA", "100", "Factura en egreso (inv�lido)", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("119", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "0.001", "Importe 3 decimales", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("120", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "0.99", "Importe con 2 decimales", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("121", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "RUC autorizado con guion: 7552-1712", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("122", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "RUC pagador con punto: 7618.4356", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("123", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "VARIOS", "00000000", "00000000", "COBRO VARIOS", "0", "Cobro varios con importe 0", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("124", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "VARIOS", "00000000", "00000000", "EGRESO VARIOS", "0", "Egreso varios con importe 0", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("125", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Documento duplicado en d�a", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("126", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Nro documento ya usado", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("127", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Ingreso con hora 00:00", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("128", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Egreso con hora 23:59", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("129", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Registro desde bot�n INGRESO directo", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("130", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Registro desde bot�n EGRESO directo", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("131", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Cajero: ADMIN (v�lido)", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("132", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Cajero vac�o", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("133", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "NOTA DE INGRESO", "100", "Cliente como pagador (inv�lido)", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("134", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Empleado", "75521712", "76184356", "NOTA DE EGRESO", "100", "Empleado como beneficiario (inv�lido)", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("135", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "VARIOS", "00000000", "00000000", "COBRO VARIOS", "100", "Medio EFECTIVO (por defecto)", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("136", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Medio GIROS sin banco", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("137", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Registro con paginaci�n activa", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("138", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Filtro activo no afecta registro", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("139", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Registro con 65 filas en tabla", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("140", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Registro tras limpiar filtros", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("141", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Ingreso con documento NIO2-9999", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("142", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Egreso con documento NIO2-9999", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("143", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "VARIOS", "00000000", "00000000", "COBRO VARIOS", "100", "COBRO VARIOS + EFECTIVO", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("144", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "VARIOS", "00000000", "00000000", "EGRESO VARIOS", "100", "EGRESO VARIOS + EFECTIVO", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("145", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Observaci�n con emoji", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("146", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Observaci�n con salto de l�nea", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("147", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Cliente", "12345678", "76184356", "RECIBO", "100", "Cliente con RECIBO v�lido", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("148", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "20123456789", "75521712", "BOLETA", "100", "Proveedor con BOLETA v�lida", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("149", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Registro con RUC autorizado = pagador", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("150", "05/11/2025", "05/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "75521712", "NOTA DE EGRESO", "100", "Proveedor paga a s� mismo", "se muestra el mensaje de inconsistencia", null)]
        public async System.Threading.Tasks.Task RegistroDeIngresosYEgresos(string caso, string fecha_Inicial, string fecha_Final, string tipo_Operacion, string tipo_Registro, string autorizado, string ruc_Autorizado, string ruc_Pagador, string documento, string importe, string observacion, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarIngresoEgreso"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("fecha_inicial", fecha_Inicial);
            argumentsOfScenario.Add("fecha_final", fecha_Final);
            argumentsOfScenario.Add("tipo_operacion", tipo_Operacion);
            argumentsOfScenario.Add("tipo_registro", tipo_Registro);
            argumentsOfScenario.Add("autorizado", autorizado);
            argumentsOfScenario.Add("ruc_autorizado", ruc_Autorizado);
            argumentsOfScenario.Add("ruc_pagador", ruc_Pagador);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("importe", importe);
            argumentsOfScenario.Add("observacion", observacion);
            argumentsOfScenario.Add("resultado", resultado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de Ingresos y Egresos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
  await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.WhenAsync(string.Format("el usuario selecciona la fecha inicial \'{0}\'", fecha_Inicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.AndAsync(string.Format("el usuario selecciona la fecha final \'{0}\'", fecha_Final), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.AndAsync(string.Format("el usuario selecciona el tipo de operacion \'{0}\'", tipo_Operacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("el usuario define el tipo de registro \'{0}\'", tipo_Registro), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("el usuario selecciona el autorizado \'{0}\'", autorizado), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("el usuario ingresa el RUC del autorizado \'{0}\'", ruc_Autorizado), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync(string.Format("el usuario ingresa el RUC del pagador \'{0}\'", ruc_Pagador), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync(string.Format("el usuario selecciona el documento \'{0}\'", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync(string.Format("el usuario define el importe \'{0}\'", importe), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync(string.Format("el usuario ingresa la observacion \'{0}\'", observacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("el usuario guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
