// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ingresos y Egresos")]
    public partial class IngresosYEgresosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Ingresos y Egresos", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "IngresosEngresos.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 3
  #line hidden
#line 4
    await testRunner.GivenAsync("el usuario accede al sistema de Ingresos/Egresos \'http://161.132.67.82:31097/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.WhenAsync("el usuario inicia sesion con usuario \'admin@plazafer.com\' y contrasena \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
    await testRunner.AndAsync("accede al modulo \'Tesoreria y Finanzas\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
    await testRunner.AndAsync("accede al submodulo \'Ingresos/Egresos\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de Ingresos y Egresos")]
        [NUnit.Framework.CategoryAttribute("RegistrarIngresoEgreso")]
        [NUnit.Framework.TestCaseAttribute("1", "01/11/2025", "01/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "120", "Prueba automatizada", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("2", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "0", "Prueba automatizada", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("3", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "0", "100", "Prueba automatizada", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("4", "01/11/2025", "01/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "120", "Prueba automatizada", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("5", "02/11/2025", "02/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "150", "Registro valido", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("6", "04/11/2025", "04/11/2025", "Pagos", "Egreso", "Proveedor", "76184356", "75521712", "NOTA DE EGRESO", "250", "Datos completos", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("7", "05/11/2025", "05/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "80", "Validacion correcta", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("8", "06/11/2025", "06/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "200", "Flujo normal", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("9", "08/11/2025", "08/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "300", "Registro exitoso", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("10", "09/11/2025", "09/11/2025", "Cobros", "Ingreso", "Empleado", "76184356", "75521712", "NOTA DE INGRESO", "60", "Prueba flujo normal", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("11", "10/11/2025", "10/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "500", "Verificacion correcta", "la operacion se realiza con exito", null)]
        [NUnit.Framework.TestCaseAttribute("12", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "0", "Sin importe", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("13", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "0", "0", "76184356", "NOTA DE EGRESO", "100", "Falta autorizado", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("14", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "0", "NOTA DE EGRESO", "100", "Falta pagador", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("15", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "75521712", "76184356", "0", "100", "Sin documento", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("16", "01/11/2025", "02/11/2025", "0", "Egreso", "Proveedor", "75521712", "76184356", "NOTA DE EGRESO", "100", "Tipo de operacion faltante", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("17", "01/11/2025", "01/11/2025", "Cobros", "0", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "100", "Sin tipo registro", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("18", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "Proveedor", "0", "0", "0", "0", "Todo vacio", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("19", "01/11/2025", "01/11/2025", "Cobros", "Ingreso", "0", "0", "76184356", "0", "0", "Sin datos", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("20", "02/11/2025", "01/11/2025", "Cobros", "Ingreso", "Empleado", "75521712", "76184356", "NOTA DE INGRESO", "150", "Fecha inicial mayor", "se muestra el mensaje de inconsistencia", null)]
        [NUnit.Framework.TestCaseAttribute("21", "01/11/2025", "01/11/2025", "Pagos", "Egreso", "0", "0", "0", "0", "0", "Caso extremo", "se muestra el mensaje de inconsistencia", null)]
        public async System.Threading.Tasks.Task RegistroDeIngresosYEgresos(string caso, string fecha_Inicial, string fecha_Final, string tipo_Operacion, string tipo_Registro, string autorizado, string ruc_Autorizado, string ruc_Pagador, string documento, string importe, string observacion, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarIngresoEgreso"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("fecha_inicial", fecha_Inicial);
            argumentsOfScenario.Add("fecha_final", fecha_Final);
            argumentsOfScenario.Add("tipo_operacion", tipo_Operacion);
            argumentsOfScenario.Add("tipo_registro", tipo_Registro);
            argumentsOfScenario.Add("autorizado", autorizado);
            argumentsOfScenario.Add("ruc_autorizado", ruc_Autorizado);
            argumentsOfScenario.Add("ruc_pagador", ruc_Pagador);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("importe", importe);
            argumentsOfScenario.Add("observacion", observacion);
            argumentsOfScenario.Add("resultado", resultado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de Ingresos y Egresos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 3
  await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.WhenAsync(string.Format("el usuario selecciona la fecha inicial \'{0}\'", fecha_Inicial), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.AndAsync(string.Format("el usuario selecciona la fecha final \'{0}\'", fecha_Final), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.AndAsync(string.Format("el usuario selecciona el tipo de operacion \'{0}\'", tipo_Operacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("el usuario define el tipo de registro \'{0}\'", tipo_Registro), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("el usuario selecciona el autorizado \'{0}\'", autorizado), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("el usuario ingresa el RUC del autorizado \'{0}\'", ruc_Autorizado), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync(string.Format("el usuario ingresa el RUC del pagador \'{0}\'", ruc_Pagador), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync(string.Format("el usuario selecciona el documento \'{0}\'", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync(string.Format("el usuario define el importe \'{0}\'", importe), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync(string.Format("el usuario ingresa la observacion \'{0}\'", observacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("el usuario guarda el registro", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
