// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NuevaCompra")]
    public partial class NuevaCompraFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "NuevaCompra", @"  Como usuario del sistema
  Quiero registrar una nueva compra
  Para asegurar que las reglas obligatorias del formulario se cumplan correctamente

  //Background:
    Given el usuario ingresa al ambiente 'http://161.132.67.82:31097/'
    When el usuario inicia sesion con usuario 'admin@plazafer.com' y contrasena 'calidad'
    And accede al modulo 'Compra'
    And accede al submodulo 'Nueva Compra'", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NuevaCompra.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de nueva compra")]
        [NUnit.Framework.CategoryAttribute("RegistrarNuevaCompra")]
        [NUnit.Framework.TestCaseAttribute("1", "0000000", "31/10/2025", "Factura electronica", "001", "00001234", "Inmediata", "CO", "Exoneradas IGV", "88008-1", "2", "20.00", "la compra se genera correctamente", null)]
        public async System.Threading.Tasks.Task RegistroDeNuevaCompra(string caso, string proveedor, string fecha, string documento, string serie, string numero_Doc, string entrega, string tipo_Pago, string tipo_Compra, string producto, string cantidad_Producto, string importe_Total, string resultado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarNuevaCompra"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("proveedor", proveedor);
            argumentsOfScenario.Add("fecha", fecha);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("serie", serie);
            argumentsOfScenario.Add("numero_doc", numero_Doc);
            argumentsOfScenario.Add("entrega", entrega);
            argumentsOfScenario.Add("tipo_pago", tipo_Pago);
            argumentsOfScenario.Add("tipo_compra", tipo_Compra);
            argumentsOfScenario.Add("producto", producto);
            argumentsOfScenario.Add("cantidad_producto", cantidad_Producto);
            argumentsOfScenario.Add("importe_total", importe_Total);
            argumentsOfScenario.Add("resultado", resultado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de nueva compra", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.WhenAsync(string.Format("el usuario selecciona el proveedor \"{0}\"", proveedor), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("define la fecha de registro \"{0}\"", fecha), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("selecciona el tipo de documento \"{0}\"", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync(string.Format("define la serie \"{0}\"", serie), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync(string.Format("define el numero de documento \"{0}\"", numero_Doc), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync(string.Format("selecciona el tipo de entrega \"{0}\"", entrega), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync(string.Format("selecciona el tipo de pago \"{0}\"", tipo_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync(string.Format("selecciona el tipo de compra \"{0}\"", tipo_Compra), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync(string.Format("registra el producto \"{0}\"", producto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync(string.Format("define la cantidad \"{0}\"", cantidad_Producto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync(string.Format("define el importe total \"{0}\"", importe_Total), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("presiona el boton \"Guardar Compra\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.ThenAsync(string.Format("{0}", resultado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
